{% set name = "flask-smorest" %}
{% set version = "0.31.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3cf65778cab6649a9acb99d75382de2bb13c1b4a5ca3b79272f0b6c936da98ef

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - apispec >=4
    - flask >=2
    - marshmallow >=3.10
    - python >=3
    - webargs >=8
    - werkzeug >=2

test:
  imports:
    - flask_smorest

about:
  home: https://github.com/marshmallow-code/flask-smorest
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: DB agnostic framework to build auto-documented REST APIs with Flask and marshmallow
  doc_url: https://flask-smorest.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/flask-smorest

extra:
  recipe-maintainers:
    - mcs07
