{% set name = "flask-smorest" %}
{% set version = "0.32.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf3d090d8490744ddb242a3dfef8b0d8f5d548548c9563815fe8a785ae91de93

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - apispec >=4
    - flask >=2
    - marshmallow >=3.10
    - python >=3
    - webargs >=8
    - werkzeug >=2

test:
  imports:
    - flask_smorest

about:
  home: https://github.com/marshmallow-code/flask-smorest
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: DB agnostic framework to build auto-documented REST APIs with Flask and marshmallow
  doc_url: https://flask-smorest.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/flask-smorest

extra:
  recipe-maintainers:
    - mcs07
