{% set name = "flask-smorest" %}
{% set version = "0.18.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9150b22dcf8bd1da5b8b7beca9b1557069c1f71404a1e14d5b7208127609ae38

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - apispec
    - flask
    - marshmallow
    - python >=3
    - webargs
    - werkzeug

test:
  imports:
    - flask_smorest

about:
  home: https://github.com/marshmallow-code/flask-smorest
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'DB agnostic framework to build auto-documented REST APIs with Flask and marshmallow'
  doc_url: https://flask-smorest.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/flask-smorest

extra:
  recipe-maintainers:
    - mcs07
