{% set name = "flask-smorest" %}
{% set version = "0.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f90187ce32f8602ad6e9f79d9b5d6c6b5e30526af6a5ff946266f2355867323

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - apispec >=4
    - flask >=1.1
    - marshmallow >=3.10
    - python >=3
    - webargs >=8
    - werkzeug >=0.15

test:
  imports:
    - flask_smorest

about:
  home: https://github.com/marshmallow-code/flask-smorest
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: DB agnostic framework to build auto-documented REST APIs with Flask and marshmallow
  doc_url: https://flask-smorest.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/flask-smorest

extra:
  recipe-maintainers:
    - mcs07
